apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i7quv5k3c-java-springboot
  janus-idp.io/tekton: i7quv5k3c-java-springboot
  backstage.io/kubernetes-id: i7quv5k3c-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i7quv5k3c-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
